### PR TITLE
Fix #67: Update README.md

### LINKED ISSUE #67: Document sed command to disable default gravity update schedule
`sed -Ei '/pihole[[:space:]]+updateGravity/I,${s/^#*/#/;b};$q1' /etc/cron.d/pihole`

- Adds a `#` to the beginning of the appropriate line in `/etc/cron.d/pihole`
- Fails (returns 1) if the line isn't found
- Nondestructive
  - Preserves line content
  - If one (or more) `#`s are already present, replaces them with a single `#`

Will submit a PR adding this to `README.md`, but it could also be added to `pihole-updatelists` _iff_ `UPDATE_GRAVITY=true`.

FWIW I'm adding this to my custom update script right after running `pihole -up`, based on the advice that it might be necessary.

### PR DESCRIPTION
**Pull request by dakotahawkins**
Add sed command `sed -Ei '/pihole[[:space:]]+updateGravity/I,${s/^#*/#/;b};$q1' /etc/cron.d/pihole` to the section on disabling the default gravity update schedule.

Fixes #67

### CODE REVIEW

**Comment by jacklul** [comment]
I'm wondering what's the story behind this long regex
I've been using `sed -e '/pihole updateGravity/ s/^#*/#/' -i /etc/cron.d/pihole` for some time and it seems to do the job fine

**Comment by dakotahawkins** [comment]
There are simpler ones that do the job, this one is similar to others I've cobbled together to do the same thing.

The line match itself just allows arbitrary whitespace between `pihole` and `updateGravity` and is case insensitive.

The sed voodoo `${s/^#*/#/;b};$q1` has the following features:
- `{ }` blocked commands, ending with `b`, which does a "Branch to label; if label is omitted, branch to end of script." That enables the following behavior:
- If it hits the `$q1` it means the replace _failed_, and the sed exits with a failure. `q` is "quit" and `1` is the exit code here.

I guess that's not really important unless you're putting it in another script (like I am) and want to respond to failures somehow.

I can change it to the simpler version if you prefer, let me know!

**Comment by dakotahawkins** [comment]
Now that I think about it, for documentation purposes the simpler one is better as long as it continues to work (which it should). I'll just change it to that. I should have considered that in the first place :)

**Comment by jacklul** [comment]
I'm now wondering why did I put a space between `/ s/`... I don't think there is any reason to put it there

**Comment by dakotahawkins** [comment]
That's important, it's the end of the line match expression and the beginning of the replace. In other words, first it matches the line, then it attempts the replace on matching lines only I think.

**Comment by dakotahawkins** [comment]
Also it just occurred to me I need to make sure running that doesn't require a `sudo`...

**Pull request merged**
